/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lame_MainActivity */

#ifndef _Included_com_example_lame_MainActivity
#define _Included_com_example_lame_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lame_MainActivity
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lame_MainActivity_getLameVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lame_MainActivity
 * Method:    convertAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_lame_MainActivity_convertAudio
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
